---
- hosts: all

  vars:
     source_file: /var/jenkins_home/workspace/Final-project-test/index.html
     destin_file: /home/ubuntu/index.html


  tasks:
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest 

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Download httpd image
      docker_image:
           name: httpd
           tag: latest
           source: pull

    - name: Launching HTTPD container
      docker_container:
           name: httpd
           image: httpd
           state: started
           exposed_ports:
           - "80"
           ports: 
           - "80:80"
    
    - name: Copy file to server
      copy: src={{ source_file }} dest={{ destin_file }} mode=0666
    
    - name: Copy file to docker container
      shell: "docker cp /home/ubuntu/index.html httpd:/usr/local/apache2/htdocs/"
